In [1]:
import numpy as np

In [8]:
dataset = np.loadtxt('/content/sample_data/space.csv', delimiter = ';', dtype=str, encoding='utf-8')

In [10]:
print(dataset)

[['\ufeffNum' 'Company Name' 'Location' ... 'Status Rocket' ' Cost'
  'Status Mission']
 ['0' 'SpaceX' 'LC-39A Kennedy Space Center Florida USA' ...
  'StatusActive' '50.0 ' 'Success']
 ['1' 'CASC' 'Site 9401 (SLS-2) Jiuquan Satellite Launch Center China'
  ... 'StatusActive' '29.75 ' 'Success']
 ...
 ['4321' 'US Navy' 'LC-18A Cape Canaveral AFS Florida USA' ...
  'StatusRetired' '0' 'Failure']
 ['4322' 'RVSN USSR' 'Site 1/5 Baikonur Cosmodrome Kazakhstan' ...
  'StatusRetired' '0' 'Success']
 ['4323' 'RVSN USSR' 'Site 1/5 Baikonur Cosmodrome Kazakhstan' ...
  'StatusRetired' '0' 'Success']]


1)

In [25]:
np.argwhere(dataset == 'Status Mission')

array([[0, 7]])

In [17]:
status = dataset[1:, 7]
print(status)

['Success' 'Success' 'Success' ... 'Failure' 'Success' 'Success']


In [18]:
total = len(status)
print(total)

4324


In [19]:
sucesso = np.sum(status == "Success")
print(sucesso)

3879


In [21]:
porcentagem = sucesso / total * 100
print(f"{porcentagem:.2f}%")

89.71%


2)

In [26]:
np.argwhere(dataset == ' Cost')

array([[0, 6]])

In [28]:
gasto = dataset[1:, 6].astype(float)
print(gasto)

[50.   29.75  0.   ...  0.    0.    0.  ]


In [29]:
gasto_valido = gasto[gasto > 0]
print(gasto_valido)

[  50.     29.75   65.    145.     64.68   48.5    50.     90.     46.
   28.3    29.15   29.75    7.5    64.68   50.     29.15   29.75   50.
    7.5    30.8    50.     29.75   50.      5.3    12.    112.5   120.
   48.5    50.     29.15   48.5   153.     30.8    48.5    50.     29.15
   50.     48.5    29.75  200.     50.     85.    115.     90.     48.5
    7.5    50.     50.    200.     29.75   29.15   50.     41.8    65.
   64.68   50.     21.     48.5    48.5     7.5    50.     64.68   31.
  200.     50.     29.15   64.68   85.     29.15    7.5    40.     65.
   64.68   48.5    29.75  112.5     5.3    64.68   41.8   164.     48.5
    7.5    29.15    7.5   153.     50.    200.     65.     48.5    48.5
   30.8    50.     62.     65.     37.      7.5    90.     29.15  200.
   50.      5.3    65.     50.     64.68   21.      7.5    50.     64.68
   29.15   85.     90.     48.5    21.     29.15    7.5    37.     29.15
   50.     50.    200.      5.3   350.     39.     50.     29.15   4

In [32]:
print(np.mean(gasto_valido))

153.7921991701245


3)

In [33]:
np.argwhere(dataset == 'Location')

array([[0, 2]])

In [36]:
loc = dataset[1:, 2]
print(loc)

['LC-39A Kennedy Space Center Florida USA'
 'Site 9401 (SLS-2) Jiuquan Satellite Launch Center China'
 'Pad A Boca Chica Texas USA' ... 'LC-18A Cape Canaveral AFS Florida USA'
 'Site 1/5 Baikonur Cosmodrome Kazakhstan'
 'Site 1/5 Baikonur Cosmodrome Kazakhstan']


In [38]:
us = np.char.find(loc, 'USA') >= 0
print(us)

[ True False  True ...  True False False]


In [39]:
print(np.sum(us == True))

1344


4)

In [40]:
np.argwhere(dataset == 'Company Name')

array([[0, 1]])

In [41]:
index_spacex = np.argwhere(dataset == 'SpaceX')
print(index_spacex)

[[  1   1]
 [  3   1]
 [  9   1]
 [ 18   1]
 [ 21   1]
 [ 24   1]
 [ 26   1]
 [ 35   1]
 [ 42   1]
 [ 46   1]
 [ 50   1]
 [ 57   1]
 [ 58   1]
 [ 63   1]
 [ 70   1]
 [ 79   1]
 [ 88   1]
 [114   1]
 [120   1]
 [130   1]
 [133   1]
 [137   1]
 [142   1]
 [147   1]
 [159   1]
 [161   1]
 [171   1]
 [176   1]
 [184   1]
 [186   1]
 [195   1]
 [211   1]
 [218   1]
 [224   1]
 [227   1]
 [229   1]
 [234   1]
 [240   1]
 [242   1]
 [245   1]
 [252   1]
 [258   1]
 [260   1]
 [267   1]
 [270   1]
 [273   1]
 [277   1]
 [289   1]
 [293   1]
 [297   1]
 [311   1]
 [315   1]
 [317   1]
 [324   1]
 [327   1]
 [332   1]
 [338   1]
 [341   1]
 [342   1]
 [350   1]
 [356   1]
 [359   1]
 [364   1]
 [367   1]
 [372   1]
 [379   1]
 [414   1]
 [419   1]
 [423   1]
 [432   1]
 [439   1]
 [442   1]
 [446   1]
 [458   1]
 [470   1]
 [472   1]
 [500   1]
 [505   1]
 [507   1]
 [515   1]
 [517   1]
 [523   1]
 [539   1]
 [542   1]
 [545   1]
 [549   1]
 [563   1]
 [575   1]
 [581   1]
 [587   1]
 [614   1]

In [43]:
index_spacex[:,0]

array([  1,   3,   9,  18,  21,  24,  26,  35,  42,  46,  50,  57,  58,
        63,  70,  79,  88, 114, 120, 130, 133, 137, 142, 147, 159, 161,
       171, 176, 184, 186, 195, 211, 218, 224, 227, 229, 234, 240, 242,
       245, 252, 258, 260, 267, 270, 273, 277, 289, 293, 297, 311, 315,
       317, 324, 327, 332, 338, 341, 342, 350, 356, 359, 364, 367, 372,
       379, 414, 419, 423, 432, 439, 442, 446, 458, 470, 472, 500, 505,
       507, 515, 517, 523, 539, 542, 545, 549, 563, 575, 581, 587, 614,
       630, 648, 705, 723, 764, 801, 809, 880, 930])

In [44]:
np.argwhere(dataset == ' Cost')

array([[0, 6]])

In [45]:
spacex_custo = dataset[index_spacex[:,0], 6].astype(float)
print(spacex_custo)

[50.   0.  50.  50.  50.  50.  50.  50.  50.  50.  50.  50.  50.  50.
 50.  50.  50.  50.  50.  90.  50.  50.  50.  90.  50.  50.  50.  50.
 50.  50.  50.  50.  50.  50.  50.  50.  62.  62.  62.  50.  62.  62.
 62.  62.  62.  90.  62.  62.  62.  62.  62.  62.  62.  62.  62.  62.
 62.  62.  62.  62.  62.  62.  62.  62.  62.  62.  62.  62.  62.  62.
 62.  62.  62.  62.  56.5 62.  56.5 56.5 56.5 56.5 56.5 56.5 56.5 56.5
 56.5 56.5 56.5 56.5 56.5 56.5 59.5 59.5 59.5 59.5 59.5  7.   7.   7.
  7.   7. ]


In [46]:
print(np.max(spacex_custo))

90.0


5)

In [47]:
np.argwhere(dataset == 'Company Name')

array([[0, 1]])

In [49]:
empresas = dataset[:, 1]
print(empresas)

['Company Name' 'SpaceX' 'CASC' ... 'US Navy' 'RVSN USSR' 'RVSN USSR']


In [51]:
empresa_nome, contagem = np.unique(empresas, return_counts=True)

In [52]:
print(empresa_nome)

['AEB' 'AMBA' 'ASI' 'Arianespace' "Arm??e de l'Air" 'Blue Origin' 'Boeing'
 'CASC' 'CASIC' 'CECLES' 'CNES' 'Company Name' 'Douglas' 'EER' 'ESA'
 'Eurockot' 'ExPace' 'Exos' 'General Dynamics' 'IAI' 'ILS' 'IRGC' 'ISA'
 'ISAS' 'ISRO' 'JAXA' 'KARI' 'KCST' 'Khrunichev' 'Kosmotras' 'Land Launch'
 'Landspace' 'Lockheed' 'MHI' 'MITT' 'Martin Marietta' 'NASA' 'Northrop'
 'OKB-586' 'OneSpace' 'RAE' 'RVSN USSR' 'Rocket Lab' 'Roscosmos' 'SRC'
 'Sandia' 'Sea Launch' 'SpaceX' 'Starsem' 'ULA' 'US Air Force' 'US Navy'
 'UT' 'VKS RF' 'Virgin Orbit' 'Yuzhmash' 'i-Space']


In [53]:
print(contagem)

[   3    8    9  279    4   12  136  251    5    4    8    1    1    1
   13   13   10    4  251   11   46    1   13   30   76    7    3    5
    1   22    7    1   79   84    7  114  203   83    2    1    2 1777
   13   55    3    1   36  100    1  140  161   17    5  201    1    2
    1]


In [54]:
for empresa, i in zip(empresa_nome, contagem):
    print(f"{empresa}: {i} missões")


AEB: 3 missões
AMBA: 8 missões
ASI: 9 missões
Arianespace: 279 missões
Arm??e de l'Air: 4 missões
Blue Origin: 12 missões
Boeing: 136 missões
CASC: 251 missões
CASIC: 5 missões
CECLES: 4 missões
CNES: 8 missões
Company Name: 1 missões
Douglas: 1 missões
EER: 1 missões
ESA: 13 missões
Eurockot: 13 missões
ExPace: 10 missões
Exos: 4 missões
General Dynamics: 251 missões
IAI: 11 missões
ILS: 46 missões
IRGC: 1 missões
ISA: 13 missões
ISAS: 30 missões
ISRO: 76 missões
JAXA: 7 missões
KARI: 3 missões
KCST: 5 missões
Khrunichev: 1 missões
Kosmotras: 22 missões
Land Launch: 7 missões
Landspace: 1 missões
Lockheed: 79 missões
MHI: 84 missões
MITT: 7 missões
Martin Marietta: 114 missões
NASA: 203 missões
Northrop: 83 missões
OKB-586: 2 missões
OneSpace: 1 missões
RAE: 2 missões
RVSN USSR: 1777 missões
Rocket Lab: 13 missões
Roscosmos: 55 missões
SRC: 3 missões
Sandia: 1 missões
Sea Launch: 36 missões
SpaceX: 100 missões
Starsem: 1 missões
ULA: 140 missões
US Air Force: 161 missões
US Navy: 17 m