In [1]:
import numpy as np

# 1)

In [2]:
arr1 = np.ones(8)
arr2 = np.random.randint(0, 10, 8)

In [3]:
print(arr1)
print(arr2)

[1. 1. 1. 1. 1. 1. 1. 1.]
[1 1 9 8 1 2 4 6]


In [4]:
arr3 = (arr1 + arr2)

In [5]:
print(arr3)

[ 2.  2. 10.  9.  2.  3.  5.  7.]


In [6]:
var = arr3.sum()
print(var)

40.0


In [7]:
if var >= 40:
  mtz = arr3.reshape(4, 2)
else:
  mtz = arr3.reshape(2, 4)

print(mtz)

[[ 2.  2.]
 [10.  9.]
 [ 2.  3.]
 [ 5.  7.]]


# 2)

In [8]:
arr4 = np.arange(0, 51, 2)
arr5 = np.arange(100, 50, -2)

In [9]:
print(arr4)
print(arr5)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50]
[100  98  96  94  92  90  88  86  84  82  80  78  76  74  72  70  68  66
  64  62  60  58  56  54  52]


In [10]:
arr6 = np.sort(np.concatenate((arr4, arr5)))

In [11]:
print(arr6)

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


# 3)

a)

In [12]:
mtz_campo = np.zeros(4).reshape(2, 2)

In [13]:
print(mtz_campo)

[[0. 0.]
 [0. 0.]]


b)

In [14]:
coord = np.random.randint(0, 2, 2)
print(coord)

[0 0]


In [15]:
mtz_campo[coord[0], coord[1]] = 1
print(mtz_campo)

[[1. 0.]
 [0. 0.]]


c)

In [17]:
vict = True
for i in range(0, np.size(mtz_campo) - 1):
  x = int(input('Insira a posição X: '))
  y = int(input('Insira a posição y: '))
  if mtz_campo[x, y] == 1:
    print('Game Over!:( Try Again!')
    vict = False
    break

if vict:
  print('Congratulations! You beat the game!:)')

Insira a posição X: 0
Insira a posição y: 1
Insira a posição X: 1
Insira a posição y: 0
Insira a posição X: 1
Insira a posição y: 1
Congratulations! You beat the game!:)


# 4)

In [31]:
mtz_dim = np.random.randint(0, 10, 2)
print(mtz_dim)

[9 7]


In [32]:
mtz2 = np.ones(mtz_dim[0] * mtz_dim[1]).reshape(mtz_dim[0], mtz_dim[1])
print(mtz2)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [33]:
print(mtz2.shape)

(9, 7)


In [49]:
mtz_tam = np.prod(mtz2.shape)
print(mtz_tam)

63


In [50]:
if mtz_tam % 2 == 0: print('Vetor unidimensional com número PAR de elementos.')
else: print('Vetor unidimensional com número ÍMPAR de elementos.')

Vetor unidimensional com número ÍMPAR de elementos.


# 5)

In [73]:
np.random.seed(10)

In [74]:
mtz3 = np.random.randint(0, 51, 16).reshape(4, 4)
print(mtz3)

[[ 9 36 15  0]
 [49 28 25 29]
 [48 29 49  8]
 [ 9  0 42 40]]


a)

In [75]:
print('Média de cada linha:', np.mean(mtz3, axis = 1))
print('Média de cada coluna:', np.mean(mtz3, axis = 0))

Média de cada linha: [15.   32.75 33.5  22.75]
Média de cada coluna: [28.75 23.25 32.75 19.25]


b)

In [76]:
print('Maior média das linhas:', np.max(np.mean(mtz3, axis = 1)))
print('Maior média das colunas:', np.max(np.mean(mtz3, axis = 0)))

Maior média das linhas: 33.5
Maior média das colunas: 32.75


c)

In [106]:
contx, conty = np.unique(mtz3, return_counts = True)

In [113]:
print(contx)
print(conty)

[ 0  8  9 15 25 28 29 36 40 42 48 49]
[2 1 2 1 1 1 2 1 1 1 1 2]


In [115]:
print(contx[np.where(conty == 2)])

[ 0  9 29 49]
